printf "3\n1\nsfernandez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n2\nvduran@hallon.es\n"  | bash wireguard-install.sh
printf "3\n3\nldumont@hallon.es\n"  | bash wireguard-install.sh
printf "3\n4\ntdryden@hallon.es\n"  | bash wireguard-install.sh
printf "3\n5\nteofilo@m3d.es\n"  | bash wireguard-install.sh
printf "3\n6\nrafael@m3d.es\n"  | bash wireguard-install.sh
printf "3\n7\nrlavado@hallon.es\n"  | bash wireguard-install.sh
printf "3\n8\njinfante@hallon.es\n"  | bash wireguard-install.sh
printf "3\n9\nsleguizamon@hallon.es\n"  | bash wireguard-install.sh
printf "3\n10\nnmartinez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n11\nlesmyjosedumont@gmail.com\n"  | bash wireguard-install.sh
printf "3\n12\npmayorca@hallon.es\n"  | bash wireguard-install.sh
printf "3\n13\nmlugo@hallon.es\n"  | bash wireguard-install.sh
printf "3\n14\npsimoes@hallon.es\n"  | bash wireguard-install.sh
printf "3\n15\nlab-sysadmin@hallon.es\n"  | bash wireguard-install.sh
printf "3\n16\nvduran@hallon.es\n"  | bash wireguard-install.sh
printf "3\n18\njmartinez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n19\ncsanchez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n20\ngherrera@hallon.es\n"  | bash wireguard-install.sh
printf "3\n21\nafernandez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n22\nmpereira@hallon.es\n"  | bash wireguard-install.sh
printf "3\n23\nvictormanuelduran.vd@gmail.com\n"  | bash wireguard-install.sh
printf "3\n24\nsfernandez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n25\nsargilla@hallon.es\n"  | bash wireguard-install.sh
printf "3\n26\nsfernandez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n27\npsimoes@hallon.es\n"  | bash wireguard-install.sh
printf "3\n28\niflores@hallon.es\n"  | bash wireguard-install.sh
printf "3\n29\nlreal@hallon.es\n"  | bash wireguard-install.sh
printf "3\n30\njares@hallon.es\n"  | bash wireguard-install.sh
printf "3\n31\nmrios@hallon.es\n"  | bash wireguard-install.sh
printf "3\n32\nagranada@hallon.es\n"  | bash wireguard-install.sh
printf "3\n33\ncgonzalez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n35\nalertastecnicos@gmail.com\n"  | bash wireguard-install.sh
printf "3\n37\nadumont@hallon.es\n"  | bash wireguard-install.sh
printf "3\n38\njmiguens@hallon.es\n"  | bash wireguard-install.sh
printf "3\n39\ndherrero@hallon.es\n"  | bash wireguard-install.sh
printf "3\n40\nrbaccaro@hallon.es\n"  | bash wireguard-install.sh
printf "3\n41\ngartiles@hallon.es\n"  | bash wireguard-install.sh
printf "3\n42\navelayos@hallon.es\n"  | bash wireguard-install.sh
printf "3\n43\njsalazar@hallon.es\n"  | bash wireguard-install.sh
printf "3\n44\nmseijas06@gmail.com\n"  | bash wireguard-install.sh
printf "3\n45\nalvarez@hallon.es\n"  | bash wireguard-install.sh
printf "3\n46\narios@hallon.es\n"  | bash wireguard-install.sh
printf "3\n47\nngomez@hallon.es\n"  | bash wireguard-install.sh